# Description
# This question has two strings str_1 and str_2. We need you to complete the code in solution.py to achieve:

# Add the strings str_1 and str_2 to get a new string;
# Multiply str_1 by 2 to get a new string;
# Slice str_1 to get the data of the string index 1 to 4, that is, the part of index 1, 2, 3, to get a new string.
# Finally, return the three new strings generated by the above three operations.

# We will import the code you perfected in solution.py into main.py and run it. If your code logic runs correctly, the program will output the result of the two string operations.

# Example
# Example 1.

# The evaluator executes your code by executing the command python main.py {str_1} {str_2}, passing a and b as command line arguments, and you can see how the code is run in main.py.

# If you pass the following arguments when.

# a = 'Hello' b = 'Python'
# Your code should output.

# ('HelloPython', 'HelloHello', 'ell')
# Example 2.

# If the following parameters are passed.

# a = 'Python' b = 'Perfect'
# Your code should output.

# ('PythonPerfect', 'PythonPython', 'yth')

# Solution:

def add_repeat_slicing(str_1: str, str_2: str) -> tuple:
    """
    :param str_1: The first source string
    :param str_2: The Second source string
    :return: tuple: A tuple containing three new strings
    """
# -- write your code here --
    tup = []
    tup.append(str_1 + str_2)
    tup.append(str_1 * 2)
    tup.append(str_1[1:4])
    tup = tuple(tup)
    return tup
  
  
  
